import type { ChallengeData } from "@/types";

export function validateCodeFix(userCode: string, fixedCode: string): boolean {
  const normalize = (code: string) =>
    code
      .split("\n")
      .map((line) => line.trimEnd())
      .join("\n")
      .trim();

  return normalize(userCode) === normalize(fixedCode);
}

export interface FullChallenge extends ChallengeData {
  fixedCode: string;
}

export const CHALLENGES: FullChallenge[] = [
  {
    id: 1,
    title: "Indentation Error",
    description: "This Python function has an indentation problem that causes a syntax error.",
    language: "python",
    buggyCode: "def greet(name):\n    if name:\n    message = f\"Hello, {name}!\"\n    return message\n    return \"Hello, stranger!\"",
    fixedCode: "def greet(name):\n    if name:\n        message = f\"Hello, {name}!\"\n        return message\n    return \"Hello, stranger!\"",
    hint: "Python cares about indentation",
    difficulty: 1,
    category: "syntax",
  },
  {
    id: 2,
    title: "List Append vs Extend",
    description: "This function should flatten a list of lists into a single list, but produces nested lists.",
    language: "python",
    buggyCode: "def flatten(lists):\n    result = []\n    for lst in lists:\n        result.append(lst)\n    return result",
    fixedCode: "def flatten(lists):\n    result = []\n    for lst in lists:\n        result.extend(lst)\n    return result",
    hint: "append vs extend - what's the difference?",
    difficulty: 2,
    category: "logic",
  },
  {
    id: 3,
    title: "Mutable Default Argument",
    description: "This function behaves unexpectedly when called multiple times without arguments.",
    language: "python",
    buggyCode: "def add_item(item, items=[]):\n    items.append(item)\n    return items",
    fixedCode: "def add_item(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    return items",
    hint: "Default arguments are evaluated once in Python",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 4,
    title: "Range Off By One",
    description: "This function should print numbers 1 through 10, but misses the last number.",
    language: "python",
    buggyCode: "def print_numbers():\n    result = []\n    for i in range(1, 10):\n        result.append(i)\n    return result",
    fixedCode: "def print_numbers():\n    result = []\n    for i in range(1, 11):\n        result.append(i)\n    return result",
    hint: "range() end value is exclusive",
    difficulty: 1,
    category: "off-by-one",
  },
  {
    id: 5,
    title: "Dictionary Key Error",
    description: "This function crashes when looking up a missing key.",
    language: "python",
    buggyCode: "def get_score(scores, name):\n    return scores[name]",
    fixedCode: "def get_score(scores, name):\n    return scores.get(name, 0)",
    hint: "What happens when the key doesn't exist?",
    difficulty: 1,
    category: "runtime",
  },
  {
    id: 6,
    title: "String Immutability",
    description: "This function tries to capitalize the first letter but doesn't work.",
    language: "python",
    buggyCode: "def capitalize_first(s):\n    if s:\n        s[0] = s[0].upper()\n    return s",
    fixedCode: "def capitalize_first(s):\n    if s:\n        s = s[0].upper() + s[1:]\n    return s",
    hint: "Strings in Python are immutable",
    difficulty: 2,
    category: "runtime",
  },
  {
    id: 7,
    title: "Integer Division",
    description: "This function should return the average as a float, but returns an integer in Python 2 style.",
    language: "python",
    buggyCode: "def average(numbers):\n    total = sum(numbers)\n    return total // len(numbers)",
    fixedCode: "def average(numbers):\n    total = sum(numbers)\n    return total / len(numbers)",
    hint: "// vs / in Python",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 8,
    title: "Variable Scope Bug",
    description: "This function should count vowels but the counter resets each iteration.",
    language: "python",
    buggyCode: "def count_vowels(text):\n    vowels = \"aeiouAEIOU\"\n    for char in text:\n        count = 0\n        if char in vowels:\n            count += 1\n    return count",
    fixedCode: "def count_vowels(text):\n    vowels = \"aeiouAEIOU\"\n    count = 0\n    for char in text:\n        if char in vowels:\n            count += 1\n    return count",
    hint: "Where is the counter initialized?",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 9,
    title: "List Comprehension Fix",
    description: "This should filter even numbers and double them, but the logic is backwards.",
    language: "python",
    buggyCode: "def double_evens(numbers):\n    return [x * 2 for x in numbers if x % 2 != 0]",
    fixedCode: "def double_evens(numbers):\n    return [x * 2 for x in numbers if x % 2 == 0]",
    hint: "Check the filter condition",
    difficulty: 2,
    category: "logic",
  },
  {
    id: 10,
    title: "Recursive Base Case",
    description: "This recursive function to calculate factorial causes infinite recursion.",
    language: "python",
    buggyCode: "def factorial(n):\n    return n * factorial(n - 1)",
    fixedCode: "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)",
    hint: "Every recursion needs a base case",
    difficulty: 2,
    category: "logic",
  },
  {
    id: 11,
    title: "Dict Iteration Bug",
    description: "This function should swap dictionary keys and values, but overwrites duplicates silently.",
    language: "python",
    buggyCode: "def invert_dict(d):\n    result = {}\n    for key in d:\n        result[d[key]] = key\n    return result",
    fixedCode: "def invert_dict(d):\n    result = {}\n    for key in d:\n        value = d[key]\n        if value in result:\n            raise ValueError(f\"Duplicate value: {value}\")\n        result[value] = key\n    return result",
    hint: "What if two keys have the same value?",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 12,
    title: "Class Variable Shared",
    description: "This class shares its items list across all instances unexpectedly.",
    language: "python",
    buggyCode: "class ShoppingCart:\n    items = []\n\n    def add(self, item):\n        self.items.append(item)\n        return self.items",
    fixedCode: "class ShoppingCart:\n    def __init__(self):\n        self.items = []\n\n    def add(self, item):\n        self.items.append(item)\n        return self.items",
    hint: "Class attributes are shared between instances",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 13,
    title: "Wrong Exception Type",
    description: "This function catches the wrong exception type, letting the real error through.",
    language: "python",
    buggyCode: "def safe_divide(a, b):\n    try:\n        return a / b\n    except ValueError:\n        return 0",
    fixedCode: "def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return 0",
    hint: "What kind of error does division by zero raise?",
    difficulty: 1,
    category: "runtime",
  },
  {
    id: 14,
    title: "String Join Mistake",
    description: "This function should join words with spaces, but adds an extra space.",
    language: "python",
    buggyCode: "def join_words(words):\n    result = \"\"\n    for word in words:\n        result += word + \" \"\n    return result",
    fixedCode: "def join_words(words):\n    return \" \".join(words)",
    hint: "Python has a built-in way to join strings",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 15,
    title: "Enumerate Off By One",
    description: "This function should return a dict mapping 1-based positions to items, but starts at 0.",
    language: "python",
    buggyCode: "def ranked_items(items):\n    return {i: item for i, item in enumerate(items)}",
    fixedCode: "def ranked_items(items):\n    return {i: item for i, item in enumerate(items, 1)}",
    hint: "enumerate has a start parameter",
    difficulty: 2,
    category: "off-by-one",
  },
  {
    id: 16,
    title: "Off By One Loop",
    description: "This function should return the sum of all numbers in the list, but it's missing the last element.",
    language: "python",
    buggyCode: "def sum_list(arr):\n    total = 0\n    for i in range(len(arr) - 1):\n        total += arr[i]\n    return total",
    fixedCode: "def sum_list(arr):\n    total = 0\n    for i in range(len(arr)):\n        total += arr[i]\n    return total",
    hint: "Check the loop boundary condition",
    difficulty: 1,
    category: "off-by-one",
  },
  {
    id: 17,
    title: "Missing Return",
    description: "This function should return the largest number in a list, but it returns None.",
    language: "python",
    buggyCode: "def find_max(arr):\n    max_val = arr[0]\n    for i in range(1, len(arr)):\n        if arr[i] > max_val:\n            max_val = arr[i]",
    fixedCode: "def find_max(arr):\n    max_val = arr[0]\n    for i in range(1, len(arr)):\n        if arr[i] > max_val:\n            max_val = arr[i]\n    return max_val",
    hint: "What does the function give back?",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 18,
    title: "String Reversal Bug",
    description: "This function should reverse a string but produces wrong results.",
    language: "python",
    buggyCode: "def reverse_string(s):\n    reversed_s = \"\"\n    for i in range(len(s), 0, -1):\n        reversed_s += s[i]\n    return reversed_s",
    fixedCode: "def reverse_string(s):\n    reversed_s = \"\"\n    for i in range(len(s) - 1, -1, -1):\n        reversed_s += s[i]\n    return reversed_s",
    hint: "Check the starting index and range bounds",
    difficulty: 2,
    category: "off-by-one",
  },
  {
    id: 19,
    title: "Wrong Comparison",
    description: "This function should check if a user is an admin, but uses the wrong operator.",
    language: "python",
    buggyCode: "def is_admin(user):\n    if user[\"role\"] is \"admin\":\n        return True\n    return False",
    fixedCode: "def is_admin(user):\n    if user[\"role\"] == \"admin\":\n        return True\n    return False",
    hint: "Look at the comparison operator — is vs ==",
    difficulty: 1,
    category: "syntax",
  },
  {
    id: 20,
    title: "Fibonacci Fix",
    description: "This recursive fibonacci function returns wrong values.",
    language: "python",
    buggyCode: "def fibonacci(n):\n    if n <= 1:\n        return 1\n    return fibonacci(n - 1) + fibonacci(n - 3)",
    fixedCode: "def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)",
    hint: "Check the base case and recursive call",
    difficulty: 2,
    category: "logic",
  },
  {
    id: 21,
    title: "Boolean Check Falsy",
    description: "This function should check if a value is provided, but fails for 0 and empty string.",
    language: "python",
    buggyCode: "def has_value(val):\n    if not val:\n        return False\n    return True",
    fixedCode: "def has_value(val):\n    if val is None:\n        return False\n    return True",
    hint: "0 and '' are falsy but valid values",
    difficulty: 2,
    category: "logic",
  },
  {
    id: 22,
    title: "Shallow Copy Gotcha",
    description: "This function should create an independent copy of a nested list, but changes still affect the original.",
    language: "python",
    buggyCode: "def copy_matrix(matrix):\n    return matrix.copy()",
    fixedCode: "import copy\n\ndef copy_matrix(matrix):\n    return copy.deepcopy(matrix)",
    hint: ".copy() only does a shallow copy",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 23,
    title: "Global Variable Bug",
    description: "This function tries to modify a global counter but raises an error.",
    language: "python",
    buggyCode: "counter = 0\n\ndef increment():\n    counter += 1\n    return counter",
    fixedCode: "counter = 0\n\ndef increment():\n    global counter\n    counter += 1\n    return counter",
    hint: "How do you modify a global variable inside a function?",
    difficulty: 2,
    category: "runtime",
  },
  {
    id: 24,
    title: "Slice Assignment Bug",
    description: "This function should insert an element at the given index, but replaces the element instead.",
    language: "python",
    buggyCode: "def insert_at(lst, index, value):\n    lst[index] = value\n    return lst",
    fixedCode: "def insert_at(lst, index, value):\n    lst.insert(index, value)\n    return lst",
    hint: "Assignment replaces, insert adds",
    difficulty: 2,
    category: "logic",
  },
  {
    id: 25,
    title: "Sort Stability Bug",
    description: "This function should sort a list without modifying the original, but it mutates the input.",
    language: "python",
    buggyCode: "def get_sorted(arr):\n    return arr.sort()",
    fixedCode: "def get_sorted(arr):\n    return sorted(arr)",
    hint: "Does .sort() return a new list?",
    difficulty: 2,
    category: "logic",
  },
  {
    id: 26,
    title: "Set Membership Bug",
    description: "This function should check if all items are unique, but always returns True.",
    language: "python",
    buggyCode: "def all_unique(arr):\n    seen = set()\n    for item in arr:\n        if item in seen:\n            return True\n        seen.add(item)\n    return False",
    fixedCode: "def all_unique(arr):\n    seen = set()\n    for item in arr:\n        if item in seen:\n            return False\n        seen.add(item)\n    return True",
    hint: "Check what True and False mean here",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 27,
    title: "JSON Parse Trap",
    description: "This function should safely parse JSON, but crashes on invalid input.",
    language: "python",
    buggyCode: "import json\n\ndef safe_parse(text):\n    result = json.loads(text)\n    return result",
    fixedCode: "import json\n\ndef safe_parse(text):\n    try:\n        result = json.loads(text)\n        return result\n    except (json.JSONDecodeError, TypeError):\n        return None",
    hint: "What happens if the string isn't valid JSON?",
    difficulty: 1,
    category: "runtime",
  },
  {
    id: 28,
    title: "Lambda Closure Bug",
    description: "This should create functions that return 0, 1, 2 but all return 3.",
    language: "python",
    buggyCode: "def create_multipliers():\n    funcs = []\n    for i in range(3):\n        funcs.append(lambda: i)\n    return funcs",
    fixedCode: "def create_multipliers():\n    funcs = []\n    for i in range(3):\n        funcs.append(lambda i=i: i)\n    return funcs",
    hint: "Think about variable scoping in lambdas",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 29,
    title: "Type Coercion Bug",
    description: "This function should concatenate a number to a string, but crashes with a TypeError.",
    language: "python",
    buggyCode: "def make_label(name, count):\n    return name + \": \" + count",
    fixedCode: "def make_label(name, count):\n    return name + \": \" + str(count)",
    hint: "Python doesn't auto-convert types in concatenation",
    difficulty: 1,
    category: "runtime",
  },
  {
    id: 30,
    title: "While Loop Infinite",
    description: "This function should count down from n to 1, but runs forever.",
    language: "python",
    buggyCode: "def countdown(n):\n    result = []\n    while n > 0:\n        result.append(n)\n    return result",
    fixedCode: "def countdown(n):\n    result = []\n    while n > 0:\n        result.append(n)\n        n -= 1\n    return result",
    hint: "What changes each iteration?",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 31,
    title: "List Remove Trap",
    description: "This function should remove all occurrences of a value, but skips some.",
    language: "python",
    buggyCode: "def remove_all(lst, value):\n    for item in lst:\n        if item == value:\n            lst.remove(item)\n    return lst",
    fixedCode: "def remove_all(lst, value):\n    return [item for item in lst if item != value]",
    hint: "Modifying a list while iterating over it is dangerous",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 32,
    title: "Tuple Unpacking Error",
    description: "This function should swap two variables but doesn't work correctly.",
    language: "python",
    buggyCode: "def swap(a, b):\n    a = b\n    b = a\n    return a, b",
    fixedCode: "def swap(a, b):\n    a, b = b, a\n    return a, b",
    hint: "Python has a special syntax for swapping",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 33,
    title: "Generator vs List",
    description: "This function should return the length of filtered items, but returns 0 on second call.",
    language: "python",
    buggyCode: "def count_positives(numbers):\n    positives = (x for x in numbers if x > 0)\n    return len(list(positives))",
    fixedCode: "def count_positives(numbers):\n    positives = [x for x in numbers if x > 0]\n    return len(positives)",
    hint: "Generators can only be consumed once",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 34,
    title: "String Strip Bug",
    description: "This function should remove only leading/trailing whitespace, but also removes from middle.",
    language: "python",
    buggyCode: "def clean_string(s):\n    return s.replace(\" \", \"\")",
    fixedCode: "def clean_string(s):\n    return s.strip()",
    hint: "replace removes ALL spaces, not just edges",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 35,
    title: "Property Decorator Bug",
    description: "This class should have a read-only computed property, but it's called as a method.",
    language: "python",
    buggyCode: "class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\n    def area(self):\n        return 3.14159 * self.radius ** 2",
    fixedCode: "class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\n    @property\n    def area(self):\n        return 3.14159 * self.radius ** 2",
    hint: "How do you make a method act like an attribute?",
    difficulty: 2,
    category: "syntax",
  },
];

export function getRandomChallenge(): FullChallenge {
  return CHALLENGES[Math.floor(Math.random() * CHALLENGES.length)];
}

export function getChallengeOfTheDay(): FullChallenge {
  const today = new Date().toISOString().slice(0, 10); // "YYYY-MM-DD"
  let hash = 0;
  for (let i = 0; i < today.length; i++) {
    hash = ((hash << 5) - hash + today.charCodeAt(i)) | 0;
  }
  return CHALLENGES[Math.abs(hash) % CHALLENGES.length];
}
