import type { ChallengeData } from "@/types";

export function validateCodeFix(userCode: string, fixedCode: string): boolean {
  const normalize = (code: string) =>
    code
      .split("\n")
      .map((line) => line.trimEnd())
      .join("\n")
      .trim();

  return normalize(userCode) === normalize(fixedCode);
}

export interface FullChallenge extends ChallengeData {
  fixedCode: string;
}

export const CHALLENGES: FullChallenge[] = [
  {
    id: 1,
    title: "Off By One Loop",
    description: "This function should return the sum of all numbers in the array, but it's missing the last element.",
    language: "javascript",
    buggyCode: "function sumArray(arr) {\n  let sum = 0;\n  for (let i = 0; i < arr.length - 1; i++) {\n    sum += arr[i];\n  }\n  return sum;\n}",
    fixedCode: "function sumArray(arr) {\n  let sum = 0;\n  for (let i = 0; i < arr.length; i++) {\n    sum += arr[i];\n  }\n  return sum;\n}",
    hint: "Check the loop boundary condition",
    difficulty: 1,
    category: "off-by-one",
  },
  {
    id: 2,
    title: "Wrong Comparison",
    description: "This function should check if a user is an admin, but it always returns true.",
    language: "javascript",
    buggyCode: "function isAdmin(user) {\n  if (user.role = \"admin\") {\n    return true;\n  }\n  return false;\n}",
    fixedCode: "function isAdmin(user) {\n  if (user.role === \"admin\") {\n    return true;\n  }\n  return false;\n}",
    hint: "Look at the comparison operator",
    difficulty: 1,
    category: "syntax",
  },
  {
    id: 3,
    title: "Missing Return",
    description: "This function should return the largest number in an array, but it returns undefined.",
    language: "javascript",
    buggyCode: "function findMax(arr) {\n  let max = arr[0];\n  for (let i = 1; i < arr.length; i++) {\n    if (arr[i] > max) {\n      max = arr[i];\n    }\n  }\n}",
    fixedCode: "function findMax(arr) {\n  let max = arr[0];\n  for (let i = 1; i < arr.length; i++) {\n    if (arr[i] > max) {\n      max = arr[i];\n    }\n  }\n  return max;\n}",
    hint: "What does the function give back?",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 4,
    title: "String Reversal Bug",
    description: "This function should reverse a string but produces wrong results.",
    language: "javascript",
    buggyCode: "function reverseString(str) {\n  let reversed = \"\";\n  for (let i = str.length; i >= 0; i--) {\n    reversed += str[i];\n  }\n  return reversed;\n}",
    fixedCode: "function reverseString(str) {\n  let reversed = \"\";\n  for (let i = str.length - 1; i >= 0; i--) {\n    reversed += str[i];\n  }\n  return reversed;\n}",
    hint: "Check the starting index",
    difficulty: 2,
    category: "off-by-one",
  },
  {
    id: 5,
    title: "Async Await Trap",
    description: "This function should fetch user data and return the parsed JSON, but it doesn't wait for the result.",
    language: "javascript",
    buggyCode: "async function getUser(id) {\n  const response = fetch(\x60/api/users/\x24{id}\x60);\n  const data = await response.json();\n  return data;\n}",
    fixedCode: "async function getUser(id) {\n  const response = await fetch(\x60/api/users/\x24{id}\x60);\n  const data = await response.json();\n  return data;\n}",
    hint: "Are you waiting for all the promises?",
    difficulty: 2,
    category: "runtime",
  },
  {
    id: 6,
    title: "Array Mutation Mistake",
    description: "This function should return a new sorted array without modifying the original, but it mutates the input.",
    language: "javascript",
    buggyCode: "function getSorted(arr) {\n  return arr.sort((a, b) => a - b);\n}",
    fixedCode: "function getSorted(arr) {\n  return [...arr].sort((a, b) => a - b);\n}",
    hint: "Does .sort() create a new array?",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 7,
    title: "Closure Gotcha",
    description: "This should create functions that log 0, 1, 2 but all log 3.",
    language: "javascript",
    buggyCode: "function createLoggers() {\n  const loggers = [];\n  for (var i = 0; i < 3; i++) {\n    loggers.push(function() {\n      console.log(i);\n    });\n  }\n  return loggers;\n}",
    fixedCode: "function createLoggers() {\n  const loggers = [];\n  for (let i = 0; i < 3; i++) {\n    loggers.push(function() {\n      console.log(i);\n    });\n  }\n  return loggers;\n}",
    hint: "Think about variable scoping",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 8,
    title: "TypeError on Null",
    description: "This function crashes when the user object doesn't have an address.",
    language: "javascript",
    buggyCode: "function getCity(user) {\n  return user.address.city;\n}",
    fixedCode: "function getCity(user) {\n  return user.address?.city;\n}",
    hint: "What if address is undefined?",
    difficulty: 2,
    category: "runtime",
  },
  {
    id: 9,
    title: "Fibonacci Fix",
    description: "This recursive fibonacci function returns wrong values.",
    language: "javascript",
    buggyCode: "function fibonacci(n) {\n  if (n <= 1) return 1;\n  return fibonacci(n - 1) + fibonacci(n - 3);\n}",
    fixedCode: "function fibonacci(n) {\n  if (n <= 1) return n;\n  return fibonacci(n - 1) + fibonacci(n - 2);\n}",
    hint: "Check the base case and recursive call",
    difficulty: 2,
    category: "logic",
  },
  {
    id: 10,
    title: "Wrong Equality Check",
    description: "This function to check if two arrays are equal always returns false for identical arrays.",
    language: "javascript",
    buggyCode: "function arraysEqual(a, b) {\n  if (a.length !== b.length) return false;\n  for (let i = 0; i < a.length; i++) {\n    if (a[i] != b[i]) return false;\n  }\n  return true;\n}\n\nfunction checkArrays(arr1, arr2) {\n  if (arr1 === arr2) {\n    return true;\n  }\n  return arraysEqual(arr1, arr2);\n}",
    fixedCode: "function arraysEqual(a, b) {\n  if (a.length !== b.length) return false;\n  for (let i = 0; i < a.length; i++) {\n    if (a[i] !== b[i]) return false;\n  }\n  return true;\n}\n\nfunction checkArrays(arr1, arr2) {\n  return arraysEqual(arr1, arr2);\n}",
    hint: "How does === work with arrays?",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 11,
    title: "Indentation Error",
    description: "This Python function has an indentation problem that causes a syntax error.",
    language: "python",
    buggyCode: "def greet(name):\n    if name:\n    message = f\"Hello, {name}!\"\n    return message\n    return \"Hello, stranger!\"",
    fixedCode: "def greet(name):\n    if name:\n        message = f\"Hello, {name}!\"\n        return message\n    return \"Hello, stranger!\"",
    hint: "Python cares about indentation",
    difficulty: 1,
    category: "syntax",
  },
  {
    id: 12,
    title: "List Append vs Extend",
    description: "This function should flatten a list of lists into a single list, but produces nested lists.",
    language: "python",
    buggyCode: "def flatten(lists):\n    result = []\n    for lst in lists:\n        result.append(lst)\n    return result",
    fixedCode: "def flatten(lists):\n    result = []\n    for lst in lists:\n        result.extend(lst)\n    return result",
    hint: "append vs extend - what's the difference?",
    difficulty: 2,
    category: "logic",
  },
  {
    id: 13,
    title: "Mutable Default Argument",
    description: "This function behaves unexpectedly when called multiple times without arguments.",
    language: "python",
    buggyCode: "def add_item(item, items=[]):\n    items.append(item)\n    return items",
    fixedCode: "def add_item(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    return items",
    hint: "Default arguments are evaluated once in Python",
    difficulty: 3,
    category: "logic",
  },
  {
    id: 14,
    title: "Range Off By One",
    description: "This function should print numbers 1 through 10, but misses the last number.",
    language: "python",
    buggyCode: "def print_numbers():\n    result = []\n    for i in range(1, 10):\n        result.append(i)\n    return result",
    fixedCode: "def print_numbers():\n    result = []\n    for i in range(1, 11):\n        result.append(i)\n    return result",
    hint: "range() end value is exclusive",
    difficulty: 1,
    category: "off-by-one",
  },
  {
    id: 15,
    title: "Dictionary Key Error",
    description: "This function crashes when looking up a missing key.",
    language: "python",
    buggyCode: "def get_score(scores, name):\n    return scores[name]",
    fixedCode: "def get_score(scores, name):\n    return scores.get(name, 0)",
    hint: "What happens when the key doesn't exist?",
    difficulty: 1,
    category: "runtime",
  },
  {
    id: 16,
    title: "String Immutability",
    description: "This function tries to capitalize the first letter but doesn't work.",
    language: "python",
    buggyCode: "def capitalize_first(s):\n    if s:\n        s[0] = s[0].upper()\n    return s",
    fixedCode: "def capitalize_first(s):\n    if s:\n        s = s[0].upper() + s[1:]\n    return s",
    hint: "Strings in Python are immutable",
    difficulty: 2,
    category: "runtime",
  },
  {
    id: 17,
    title: "Integer Division",
    description: "This function should return the average as a float, but returns an integer in Python 2 style.",
    language: "python",
    buggyCode: "def average(numbers):\n    total = sum(numbers)\n    return total // len(numbers)",
    fixedCode: "def average(numbers):\n    total = sum(numbers)\n    return total / len(numbers)",
    hint: "// vs / in Python",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 18,
    title: "Variable Scope Bug",
    description: "This function should count vowels but the counter resets each iteration.",
    language: "python",
    buggyCode: "def count_vowels(text):\n    vowels = \"aeiouAEIOU\"\n    for char in text:\n        count = 0\n        if char in vowels:\n            count += 1\n    return count",
    fixedCode: "def count_vowels(text):\n    vowels = \"aeiouAEIOU\"\n    count = 0\n    for char in text:\n        if char in vowels:\n            count += 1\n    return count",
    hint: "Where is the counter initialized?",
    difficulty: 1,
    category: "logic",
  },
  {
    id: 19,
    title: "List Comprehension Fix",
    description: "This should filter even numbers and double them, but the logic is backwards.",
    language: "python",
    buggyCode: "def double_evens(numbers):\n    return [x * 2 for x in numbers if x % 2 != 0]",
    fixedCode: "def double_evens(numbers):\n    return [x * 2 for x in numbers if x % 2 == 0]",
    hint: "Check the filter condition",
    difficulty: 2,
    category: "logic",
  },
  {
    id: 20,
    title: "Recursive Base Case",
    description: "This recursive function to calculate factorial causes infinite recursion.",
    language: "python",
    buggyCode: "def factorial(n):\n    return n * factorial(n - 1)",
    fixedCode: "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)",
    hint: "Every recursion needs a base case",
    difficulty: 2,
    category: "logic",
  },
];

export function getRandomChallenge(): FullChallenge {
  return CHALLENGES[Math.floor(Math.random() * CHALLENGES.length)];
}
